Company.Designation = DGS/SNS Portugal
TaskRun.PeopleVaccinated=16:51
fileReader = app.domain.model.utils.ReaderWithHeader
#fileReader = app.domain.model.utils.ReaderWithoutHeader
#delimiter =,
delimiter =;
numberOfAttributesLegacyData=12
headerLegacyData=SNSUSerNumber;VaccineName;Dose;LotNumber;ScheduledDateTime;ArrivalDateTime;NurseAdministrationDateTime;LeavingDateTime
#headerLegacyData=SNSUSerNumber,VaccineName,Dose,LotNumber,ScheduledDateTime,ArrivalDateTime,NurseAdministrationDateTime,LeavingDateTime
splitDataTimeColumn=yes
#sortAlg = app.domain.algorithms.BubbleSort
sortAlg = app.domain.algorithms.MergeSort
brutAlg = app.domain.algorithms.BruteForce
#brutAlg = app.domain.algorithms.Benchmark