@startuml
autonumber
actor "Center Coordinator" as cord

activate cord

cord -> ":System" : starts import data from a legacy system
activate ":System"

":System" --> cord : requests the file path of data to import
deactivate ":System"

cord -> ":System" : types the required information
activate ":System"

":System" --> cord : asks for sorting criterias
deactivate ":System"

cord -> ":System" : Selects the intended criterias
activate ":System"

":System" --> cord : shows all selected data and requests confirmation
deactivate ":System"

cord -> ":System" : confirms data
activate ":System"

":System" --> cord : informs about the success of the operation
deactivate ":System"
deactivate cord

@enduml