@startuml
autonumber
'hide footbox

actor Nurse

participant ":SelectVaccinationCenterUI" as UI
participant "SelectVaccinationCenterController" as CTRL
participant ":Company" as Com
participant "vcStore:\nVaccinationCenterStore" as VcStore
participant ":VaccinationCenterMapper" as VCMapper

participant "App" as Ap
participant "app:App" as InstAp
participant "session:UserSession" as Sess

participant "eStore:\nEmployeeStore" as EmpStore
participant "empl:Employee" as Emp
participant "lvaccinationCenters: List<VaccinationCenter>" as ListVCenters
participant "lvaccinationCentersDTO : List<vaccinationCentersDTO>" as VCListDTO


note left UI : After login, this UI will run automatically

activate UI
UI->CTRL : lvaccinationCenters = getVaccinationCenters()
activate CTRL
CTRL->Com :vcStore = getVaccinationCenterStore()
activate Com
deactivate Com
CTRL->VcStore: lvaccinationCenters = getVaccinationCenters()
activate VcStore
deactivate VcStore
CTRL->VCMapper: toDTO(lvaccinationCenters)
activate VCMapper
ref over VCMapper
SD_VaccinationCenterMapper_toDTO_List
end ref
VCMapper --> CTRL : lvaccinationCentersDTO
deactivate VCMapper
deactivate CTRL

UI --> Nurse: shows the vaccination centers list
deactivate UI

activate Nurse
Nurse ->UI : selects the vaccination center to work
activate UI

UI -> CTRL : setVaccinationCenterId(vaccinationCenterId)
activate CTRL
CTRL -> Ap : app = getInstance()
activate Ap
deactivate Ap
CTRL -> InstAp : session = getCurrentUserSession()
activate InstAp
deactivate InstAp
CTRL -> Sess : email = getUserId()
activate Sess
deactivate Sess
CTRL -> Com : eStore = getEmployeeStore()
activate Com
deactivate Com
CTRL -> EmpStore : empl = getEmployeeByEmail(email)
activate EmpStore
deactivate EmpStore
CTRL -> Emp : setVaccinationCenterId(vaccinationCenterId)
activate Emp
deactivate Emp

deactivate CTRL
UI --> Nurse: Vaccination Center added with success
deactivate UI



@enduml