@startuml
autonumber
actor "Administrator" as Admin

activate Admin
Admin -> ":System" : starts the registration of a new employee
activate ":System"
":System" --> Admin : requests the required data (name, address, phone number, e-mail, Citizen Card number and role)
deactivate ":System"

Admin -> ":System" : types required information according to the data fields
activate ":System"
":System" --> Admin : presents all data and asks for confirmation
deactivate ":System"

Admin -> ":System" : confirms the data
activate ":System"
":System" --> Admin : informs about the success of the operation
deactivate ":System"

deactivate Admin

@enduml